// <auto-generated />
using System;
using CampClotNot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CampClotNot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604004934_AddScheduleItemLocationOther")]
    partial class AddScheduleItemLocationOther
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CampClotNot.Data.Entities.Activity", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ActivityId");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("EventId");

                    b.HasIndex("LocationId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.ActivityType", b =>
                {
                    b.Property<Guid>("ActivityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ActivityTypeId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ActivityTypes");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.ActivityTypeCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("ActivityTypeCategories");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Announcement", b =>
                {
                    b.Property<Guid>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Announcements");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Authority", b =>
                {
                    b.Property<Guid>("AuthorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AuthorityId");

                    b.ToTable("Authorities");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.AwardType", b =>
                {
                    b.Property<Guid>("AwardTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AwardTypeId");

                    b.ToTable("AwardTypes");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.BoardSpace", b =>
                {
                    b.Property<Guid>("SpaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("IconAssetPath")
                        .HasColumnType("text");

                    b.Property<int>("SpaceIndex")
                        .HasColumnType("integer");

                    b.Property<float>("XPos")
                        .HasColumnType("real");

                    b.Property<float>("YPos")
                        .HasColumnType("real");

                    b.HasKey("SpaceId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("EventId");

                    b.ToTable("BoardSpaces");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.CamperAward", b =>
                {
                    b.Property<Guid>("AwardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AwardTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BonusStars")
                        .HasColumnType("integer");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AwardId");

                    b.HasIndex("AwardTypeId");

                    b.HasIndex("EventId");

                    b.HasIndex("GroupId");

                    b.ToTable("CamperAwards");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Capability", b =>
                {
                    b.Property<Guid>("CapabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CapabilityId");

                    b.ToTable("Capabilities");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.CurrencyType", b =>
                {
                    b.Property<Guid>("CurrencyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CurrencyTypeId");

                    b.ToTable("CurrencyTypes");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EffDate")
                        .HasColumnType("date");

                    b.Property<Guid>("EventTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ExpDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ThemeId")
                        .HasColumnType("uuid");

                    b.HasKey("EventId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("ThemeId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.EventCapability", b =>
                {
                    b.Property<Guid>("EventCapabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CapabilityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.HasKey("EventCapabilityId");

                    b.HasIndex("CapabilityId");

                    b.HasIndex("EventId");

                    b.ToTable("EventCapabilities");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.EventScheduleItemType", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScheduleItemTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("EventId", "ScheduleItemTypeId");

                    b.HasIndex("ScheduleItemTypeId");

                    b.ToTable("EventScheduleItemTypes");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.EventType", b =>
                {
                    b.Property<Guid>("EventTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EventTypeId");

                    b.ToTable("EventTypes");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Group", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CabinDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenAssetPath")
                        .HasColumnType("text");

                    b.HasKey("GroupId");

                    b.HasIndex("EventId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.GroupBoardPos", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("SpaceIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GroupId");

                    b.ToTable("GroupBoardPositions");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.IncidentReport", b =>
                {
                    b.Property<Guid>("IncidentReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AcknowledgedByName")
                        .HasColumnType("text");

                    b.Property<Guid?>("AcknowledgedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCompleted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfIncident")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IncidentLocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("IncidentLocationOther")
                        .HasColumnType("text");

                    b.Property<bool>("IsAcknowledged")
                        .HasColumnType("boolean");

                    b.Property<string>("PersonsInvolved")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecommendedAction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReportType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubmittedByName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubmittedByRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SubmittedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("IncidentReportId");

                    b.HasIndex("EventId");

                    b.HasIndex("IncidentLocationId");

                    b.ToTable("IncidentReports");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.InfoPage", b =>
                {
                    b.Property<Guid>("PageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconEmoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedByUserId")
                        .HasColumnType("uuid");

                    b.HasKey("PageId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("UpdatedByUserId");

                    b.ToTable("InfoPages");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Location", b =>
                {
                    b.Property<Guid>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ImageContentType")
                        .HasColumnType("text");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.ScheduleItem", b =>
                {
                    b.Property<Guid>("ScheduleItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AppliesToAllGroups")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("CampDay")
                        .HasColumnType("date");

                    b.Property<Guid>("CampEventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("LocationOther")
                        .HasColumnType("text");

                    b.Property<int?>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("PresenterBio")
                        .HasColumnType("text");

                    b.Property<string>("PresenterName")
                        .HasColumnType("text");

                    b.Property<Guid>("ScheduleItemTypeId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ScheduleItemId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("CampEventId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("LocationId");

                    b.HasIndex("ScheduleItemTypeId");

                    b.ToTable("ScheduleItems");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.ScheduleItemGroup", b =>
                {
                    b.Property<Guid>("ScheduleItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.HasKey("ScheduleItemId", "GroupId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("GroupId");

                    b.HasIndex("LocationId");

                    b.ToTable("ScheduleItemGroups");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.ScheduleItemType", b =>
                {
                    b.Property<Guid>("ScheduleItemTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ScheduleItemTypeId");

                    b.ToTable("ScheduleItemTypes");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.ScriptedBlockHit", b =>
                {
                    b.Property<Guid>("ScriptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CampDay")
                        .HasColumnType("integer");

                    b.Property<int>("DestinationSpaceIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsTriggered")
                        .HasColumnType("boolean");

                    b.HasKey("ScriptId");

                    b.HasIndex("EventId");

                    b.HasIndex("GroupId");

                    b.ToTable("ScriptedBlockHits");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.ScriptedMiniGame", b =>
                {
                    b.Property<Guid>("ScriptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<int>("CampDay")
                        .HasColumnType("integer");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsTriggered")
                        .HasColumnType("boolean");

                    b.HasKey("ScriptId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("EventId");

                    b.ToTable("ScriptedMiniGames");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Sponsor", b =>
                {
                    b.Property<Guid>("SponsorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactName")
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("LogoContentType")
                        .HasColumnType("text");

                    b.Property<byte[]>("LogoData")
                        .HasColumnType("bytea");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("SponsorId");

                    b.HasIndex("EventId");

                    b.ToTable("Sponsors");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.StaffMember", b =>
                {
                    b.Property<Guid>("StaffMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarEmoji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CampEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LinkedUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PhotoContentType")
                        .HasColumnType("text");

                    b.Property<byte[]>("PhotoData")
                        .HasColumnType("bytea");

                    b.Property<string>("PhotoObjectPosition")
                        .HasColumnType("text");

                    b.Property<string>("RoleTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("StaffMemberId");

                    b.HasIndex("CampEventId");

                    b.HasIndex("LinkedUserId");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Theme", b =>
                {
                    b.Property<Guid>("ThemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColorPalette")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FontConfig")
                        .HasColumnType("text");

                    b.Property<string>("LogoAssetPath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("ThemeId");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Transaction", b =>
                {
                    b.Property<Guid>("TxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrencyTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoggedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VoidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VoidedBy")
                        .HasColumnType("text");

                    b.HasKey("TxId");

                    b.HasIndex("CurrencyTypeId");

                    b.HasIndex("GroupId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserRoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.UserAuthorityLink", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorityId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "AuthorityId");

                    b.HasIndex("AuthorityId");

                    b.ToTable("UserAuthorityLinks");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserRoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.UserRoleAuthorityLink", b =>
                {
                    b.Property<Guid>("UserRoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorityId")
                        .HasColumnType("uuid");

                    b.HasKey("UserRoleId", "AuthorityId");

                    b.HasIndex("AuthorityId");

                    b.ToTable("UserRoleAuthorityLinks");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Activity", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.ActivityType", "ActivityType")
                        .WithMany("Activities")
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.Event", "Event")
                        .WithMany("Activities")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("ActivityType");

                    b.Navigation("Event");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.ActivityType", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.ActivityTypeCategory", "Category")
                        .WithMany("ActivityTypes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Announcement", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.BoardSpace", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.Activity", "Activity")
                        .WithMany("BoardSpaces")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.Event", "Event")
                        .WithMany("BoardSpaces")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.CamperAward", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.AwardType", "AwardType")
                        .WithMany("CamperAwards")
                        .HasForeignKey("AwardTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.Event", "Event")
                        .WithMany("CamperAwards")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.Group", "Group")
                        .WithMany("CamperAwards")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwardType");

                    b.Navigation("Event");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Event", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.EventType", "EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.Theme", "Theme")
                        .WithMany("Events")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventType");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.EventCapability", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.Capability", "Capability")
                        .WithMany("EventCapabilities")
                        .HasForeignKey("CapabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.Event", "Event")
                        .WithMany("EventCapabilities")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capability");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.EventScheduleItemType", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.ScheduleItemType", "ScheduleItemType")
                        .WithMany()
                        .HasForeignKey("ScheduleItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("ScheduleItemType");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Group", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.Event", "Event")
                        .WithMany("Groups")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.GroupBoardPos", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.Group", "Group")
                        .WithOne("BoardPos")
                        .HasForeignKey("CampClotNot.Data.Entities.GroupBoardPos", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.IncidentReport", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.Location", "IncidentLocation")
                        .WithMany()
                        .HasForeignKey("IncidentLocationId");

                    b.Navigation("Event");

                    b.Navigation("IncidentLocation");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.InfoPage", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.User", "UpdatedBy")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UpdatedBy");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.ScheduleItem", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId");

                    b.HasOne("CampClotNot.Data.Entities.Event", "CampEvent")
                        .WithMany()
                        .HasForeignKey("CampEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("CampClotNot.Data.Entities.ScheduleItemType", "ScheduleItemType")
                        .WithMany()
                        .HasForeignKey("ScheduleItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("CampEvent");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Location");

                    b.Navigation("ScheduleItemType");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.ScheduleItemGroup", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId");

                    b.HasOne("CampClotNot.Data.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("CampClotNot.Data.Entities.ScheduleItem", "ScheduleItem")
                        .WithMany("ItemGroups")
                        .HasForeignKey("ScheduleItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Group");

                    b.Navigation("Location");

                    b.Navigation("ScheduleItem");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.ScriptedBlockHit", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.Event", "Event")
                        .WithMany("ScriptedBlockHits")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.Group", "Group")
                        .WithMany("ScriptedBlockHits")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.ScriptedMiniGame", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.Activity", "Activity")
                        .WithMany("ScriptedMiniGames")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.Event", "Event")
                        .WithMany("ScriptedMiniGames")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Sponsor", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.StaffMember", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.Event", "CampEvent")
                        .WithMany()
                        .HasForeignKey("CampEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.User", "LinkedUser")
                        .WithMany()
                        .HasForeignKey("LinkedUserId");

                    b.Navigation("CampEvent");

                    b.Navigation("LinkedUser");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Transaction", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.CurrencyType", "CurrencyType")
                        .WithMany("Transactions")
                        .HasForeignKey("CurrencyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.Group", "Group")
                        .WithMany("Transactions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrencyType");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.User", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("CampClotNot.Data.Entities.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.UserAuthorityLink", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.Authority", "Authority")
                        .WithMany("UserLinks")
                        .HasForeignKey("AuthorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.User", "User")
                        .WithMany("AuthorityLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Authority");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.UserRoleAuthorityLink", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.Authority", "Authority")
                        .WithMany("RoleLinks")
                        .HasForeignKey("AuthorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.UserRole", "UserRole")
                        .WithMany("AuthorityLinks")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Authority");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Activity", b =>
                {
                    b.Navigation("BoardSpaces");

                    b.Navigation("ScriptedMiniGames");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.ActivityType", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.ActivityTypeCategory", b =>
                {
                    b.Navigation("ActivityTypes");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Authority", b =>
                {
                    b.Navigation("RoleLinks");

                    b.Navigation("UserLinks");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.AwardType", b =>
                {
                    b.Navigation("CamperAwards");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Capability", b =>
                {
                    b.Navigation("EventCapabilities");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.CurrencyType", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Event", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("BoardSpaces");

                    b.Navigation("CamperAwards");

                    b.Navigation("EventCapabilities");

                    b.Navigation("Groups");

                    b.Navigation("ScriptedBlockHits");

                    b.Navigation("ScriptedMiniGames");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.EventType", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Group", b =>
                {
                    b.Navigation("BoardPos");

                    b.Navigation("CamperAwards");

                    b.Navigation("ScriptedBlockHits");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.ScheduleItem", b =>
                {
                    b.Navigation("ItemGroups");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Theme", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.User", b =>
                {
                    b.Navigation("AuthorityLinks");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.UserRole", b =>
                {
                    b.Navigation("AuthorityLinks");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
