// <auto-generated />
using System;
using CampClotNot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CampClotNot.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CampClotNot.Data.Entities.Activity", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ActivityId");

                    b.HasIndex("ActivityTypeId");

                    b.HasIndex("EventId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.ActivityType", b =>
                {
                    b.Property<Guid>("ActivityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ActivityTypeId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ActivityTypes");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.ActivityTypeCategory", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("ActivityTypeCategories");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Authority", b =>
                {
                    b.Property<Guid>("AuthorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AuthorityId");

                    b.ToTable("Authorities");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.AwardType", b =>
                {
                    b.Property<Guid>("AwardTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AwardTypeId");

                    b.ToTable("AwardTypes");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.BoardSpace", b =>
                {
                    b.Property<Guid>("SpaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("IconAssetPath")
                        .HasColumnType("text");

                    b.Property<int>("SpaceIndex")
                        .HasColumnType("integer");

                    b.Property<float>("XPos")
                        .HasColumnType("real");

                    b.Property<float>("YPos")
                        .HasColumnType("real");

                    b.HasKey("SpaceId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("EventId");

                    b.ToTable("BoardSpaces");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.CamperAward", b =>
                {
                    b.Property<Guid>("AwardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AwardTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BonusStars")
                        .HasColumnType("integer");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AwardId");

                    b.HasIndex("AwardTypeId");

                    b.HasIndex("EventId");

                    b.HasIndex("GroupId");

                    b.ToTable("CamperAwards");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Capability", b =>
                {
                    b.Property<Guid>("CapabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CapabilityId");

                    b.ToTable("Capabilities");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.CurrencyType", b =>
                {
                    b.Property<Guid>("CurrencyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CurrencyTypeId");

                    b.ToTable("CurrencyTypes");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("EffDate")
                        .HasColumnType("date");

                    b.Property<Guid>("EventTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("ExpDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ThemeId")
                        .HasColumnType("uuid");

                    b.HasKey("EventId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("ThemeId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.EventCapability", b =>
                {
                    b.Property<Guid>("EventCapabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CapabilityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.HasKey("EventCapabilityId");

                    b.HasIndex("CapabilityId");

                    b.HasIndex("EventId");

                    b.ToTable("EventCapabilities");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.EventType", b =>
                {
                    b.Property<Guid>("EventTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EventTypeId");

                    b.ToTable("EventTypes");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Group", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CabinDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TokenAssetPath")
                        .HasColumnType("text");

                    b.HasKey("GroupId");

                    b.HasIndex("EventId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.GroupBoardPos", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<int>("SpaceIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("GroupId");

                    b.ToTable("GroupBoardPositions");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.ScriptedBlockHit", b =>
                {
                    b.Property<Guid>("ScriptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CampDay")
                        .HasColumnType("integer");

                    b.Property<int>("DestinationSpaceIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsTriggered")
                        .HasColumnType("boolean");

                    b.HasKey("ScriptId");

                    b.HasIndex("EventId");

                    b.HasIndex("GroupId");

                    b.ToTable("ScriptedBlockHits");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.ScriptedMiniGame", b =>
                {
                    b.Property<Guid>("ScriptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<int>("CampDay")
                        .HasColumnType("integer");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsTriggered")
                        .HasColumnType("boolean");

                    b.HasKey("ScriptId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("EventId");

                    b.ToTable("ScriptedMiniGames");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Theme", b =>
                {
                    b.Property<Guid>("ThemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColorPalette")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FontConfig")
                        .HasColumnType("text");

                    b.Property<string>("LogoAssetPath")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("ThemeId");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Transaction", b =>
                {
                    b.Property<Guid>("TxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CurrencyTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoggedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VoidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VoidedBy")
                        .HasColumnType("text");

                    b.HasKey("TxId");

                    b.HasIndex("CurrencyTypeId");

                    b.HasIndex("GroupId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserRoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.UserAuthorityLink", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorityId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "AuthorityId");

                    b.HasIndex("AuthorityId");

                    b.ToTable("UserAuthorityLinks");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserRoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.UserRoleAuthorityLink", b =>
                {
                    b.Property<Guid>("UserRoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuthorityId")
                        .HasColumnType("uuid");

                    b.HasKey("UserRoleId", "AuthorityId");

                    b.HasIndex("AuthorityId");

                    b.ToTable("UserRoleAuthorityLinks");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Activity", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.ActivityType", "ActivityType")
                        .WithMany("Activities")
                        .HasForeignKey("ActivityTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.Event", "Event")
                        .WithMany("Activities")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActivityType");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.ActivityType", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.ActivityTypeCategory", "Category")
                        .WithMany("ActivityTypes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.BoardSpace", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.Activity", "Activity")
                        .WithMany("BoardSpaces")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.Event", "Event")
                        .WithMany("BoardSpaces")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.CamperAward", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.AwardType", "AwardType")
                        .WithMany("CamperAwards")
                        .HasForeignKey("AwardTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.Event", "Event")
                        .WithMany("CamperAwards")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.Group", "Group")
                        .WithMany("CamperAwards")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwardType");

                    b.Navigation("Event");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Event", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.EventType", "EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.Theme", "Theme")
                        .WithMany("Events")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventType");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.EventCapability", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.Capability", "Capability")
                        .WithMany("EventCapabilities")
                        .HasForeignKey("CapabilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.Event", "Event")
                        .WithMany("EventCapabilities")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capability");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Group", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.Event", "Event")
                        .WithMany("Groups")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.GroupBoardPos", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.Group", "Group")
                        .WithOne("BoardPos")
                        .HasForeignKey("CampClotNot.Data.Entities.GroupBoardPos", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.ScriptedBlockHit", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.Event", "Event")
                        .WithMany("ScriptedBlockHits")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.Group", "Group")
                        .WithMany("ScriptedBlockHits")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.ScriptedMiniGame", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.Activity", "Activity")
                        .WithMany("ScriptedMiniGames")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.Event", "Event")
                        .WithMany("ScriptedMiniGames")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Transaction", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.CurrencyType", "CurrencyType")
                        .WithMany("Transactions")
                        .HasForeignKey("CurrencyTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.Group", "Group")
                        .WithMany("Transactions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrencyType");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.User", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.UserAuthorityLink", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.Authority", "Authority")
                        .WithMany("UserLinks")
                        .HasForeignKey("AuthorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.User", "User")
                        .WithMany("AuthorityLinks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Authority");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.UserRoleAuthorityLink", b =>
                {
                    b.HasOne("CampClotNot.Data.Entities.Authority", "Authority")
                        .WithMany("RoleLinks")
                        .HasForeignKey("AuthorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampClotNot.Data.Entities.UserRole", "UserRole")
                        .WithMany("AuthorityLinks")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Authority");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Activity", b =>
                {
                    b.Navigation("BoardSpaces");

                    b.Navigation("ScriptedMiniGames");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.ActivityType", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.ActivityTypeCategory", b =>
                {
                    b.Navigation("ActivityTypes");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Authority", b =>
                {
                    b.Navigation("RoleLinks");

                    b.Navigation("UserLinks");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.AwardType", b =>
                {
                    b.Navigation("CamperAwards");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Capability", b =>
                {
                    b.Navigation("EventCapabilities");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.CurrencyType", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Event", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("BoardSpaces");

                    b.Navigation("CamperAwards");

                    b.Navigation("EventCapabilities");

                    b.Navigation("Groups");

                    b.Navigation("ScriptedBlockHits");

                    b.Navigation("ScriptedMiniGames");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.EventType", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Group", b =>
                {
                    b.Navigation("BoardPos");

                    b.Navigation("CamperAwards");

                    b.Navigation("ScriptedBlockHits");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.Theme", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.User", b =>
                {
                    b.Navigation("AuthorityLinks");
                });

            modelBuilder.Entity("CampClotNot.Data.Entities.UserRole", b =>
                {
                    b.Navigation("AuthorityLinks");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
